name: Update Json

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GA_ID: ${{ secrets.GA_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: setup frontend
        run: cd frontend && npm ci

      - name: build cdk
        run: |
          git clone https://github.com/aws/aws-cdk.git
          cd aws-cdk
          yarn
          npx lerna run build --scope=aws-cdk-lib --skip-nx-cache

      - name: create json
        run: |
          git clone https://github.com/badmintoncryer/cdk-unsupported-property
          cd cdk-unsupported-property
          npm install
          npm i -g ts-node
          ts-node src/index.ts ../aws-cdk/packages
          mv missingProperties.json ../frontend/app/missingProperties.json

      - name: clean up
        run: |
          rm -rf aws-cdk
          rm -rf cdk-unsupported-property

      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update missingProperties.json file
          delete-branch: true
          title: Update missingProperties.json file
          reviewers: badmintoncryer
